### ISSUE TITLE
Vistas crashing issue on launch

### ISSUE THREAD

**Issue by Hyrus** [LudoCrypt/Vistas#17]
Title says it, but I am running on the latest version of Vistas V1.4.4, Fabric API 0.42.1 and fabric loader 0.11.6 on 1.17.1

Here is the portion of the logs where its crashing
```
[15:58:42] [Render thread/WARN]: Method overwrite conflict for method_22920 in mixins.iris.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[15:58:42] [Render thread/WARN]: @Redirect conflict. Skipping vistas.mixins.json:TitleScreenMixin->@Redirect::vistas$overrider$render(Lnet/minecraft/class_766;FF)V with priority 1000, already redirected by slight-gui-modifications.mixins.json:MixinTitleScreen->@Redirect::thing(Lnet/minecraft/class_766;FF)V with priority 1000
[15:58:43] [Render thread/WARN]: @Redirect conflict. Skipping vistas.mixins.json:TitleScreenMixin->@Redirect::vistas$overrider$render(Lnet/minecraft/class_766;FF)V with priority 1000, already redirected by slight-gui-modifications.mixins.json:MixinTitleScreen->@Redirect::thing(Lnet/minecraft/class_766;FF)V with priority 1000
[15:58:43] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[15:58:43] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[15:58:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[15:58:43] [Render thread/INFO]: [STDERR]: 	... 2 more
[15:58:43] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[15:58:43] [Render thread/INFO]: [STDERR]: 	... 7 more
[15:58:43] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector vistas$overrider$render(Lnet/minecraft/class_766;FF)V in vistas.mixins.json:TitleScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap vistas-refmap.json
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[15:58:43] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[15:58:43] [Render thread/INFO]: [STDERR]: 	... 14 more
```

**Comment by Hyrus** [comment]
After doing some testing, its not Iris it seems to be just slight gui modifications which i see is a known issue

**Comment by LudoCrypt** [comment]
Duplicate Issue
